import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiLaravel,
  SiTailwindcss,
  SiAlpinedotjs,
  SiLivewire,
  SiStatamic,
  SiFlutter,
  SiReact,
  SiVuedotjs,
  SiAngular,
  SiSwift,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiOracle,
  SiSqlite,
  SiFirebase,
  SiGit,
  SiGitlab,
  SiDocker,
  SiPython,
  SiJira,
  SiSentry,
  SiPhp,
  SiMeilisearch,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaPhone,
  FaUpwork,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  phone: FaPhone,
  upwork: FaUpwork,

  // Noile iconițe adăugate pentru secțiunea Technical Skills
  laravel: SiLaravel,
  tailwind: SiTailwindcss,
  alpine: SiAlpinedotjs,
  livewire: SiLivewire,
  statamic: SiStatamic,
  flutter: SiFlutter,
  react: SiReact,
  vue: SiVuedotjs,
  angular: SiAngular,
  swift: SiSwift,
  mysql: SiMysql,
  postgres: SiPostgresql,
  mongodb: SiMongodb,
  oracle: SiOracle,
  sqlite: SiSqlite,
  firebase: SiFirebase,
  git: SiGit,
  gitlab: SiGitlab,
  docker: SiDocker,
  python: SiPython,
  jira: SiJira,
  sentry: SiSentry,
  php: SiPhp,
  meilisearch: SiMeilisearch,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
